freebsd_instance:
  image_family: freebsd-12-1

task:
  name: FreeBSD 12.1
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - pkg install -y pkgconf fusefs-libs fusefs-libs3
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --all --no-deps --features=abi-7-21
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all --all-targets -- --skip=channel::test::mount_unmount
    - cargo test --all --all-targets --features=abi-7-21 -- --skip=channel::test::mount_unmount
  before_cache_script: rm -rf $CARGO_HOME/registry/index
