accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Zlib",
]

targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true

no-clearly-defined = true

workarounds = ["ring"]
