[project]
name = "mountpoint-s3-packaging"
version = "0.1.0"
description = "Packaging tools for Mountpoint-S3"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.0.0",
]

