name: Integration tests

on:
  push:
    branches: [ "main" ]
  merge_group:
    types: [ "checks_requested" ]

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml
    with:
      ref: ${{ github.event.after }}
