name: Integration tests

on:
  push:
    branches: [ "main", "wf-changes/**" ]
  merge_group:
    types: [ "checks_requested" ]
  schedule:
    - cron: "45 6 * * *" # Daily at 06:45 UTC
  workflow_dispatch:
    inputs:
      ref:
        description: "Git reference or commit hash to run the workflow against."
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    if: github.event_name != 'schedule' || github.repository == 'awslabs/mountpoint-s3'
    name: Integration
    uses: ./.github/workflows/integration.yml
    with:
      ref: ${{ github.sha }}
