name: Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [ "checks_requested" ]

permissions:
  contents: read

jobs:
  packages:
    name: Package ${{ matrix.runner.name }}
    runs-on: ${{ matrix.runner.tags }}

    strategy:
      matrix:
        runner:
        - name: x86_64
          tags: [ubuntu-22.04] # GitHub-hosted
        - name: aarch64
          tags: [self-hosted, linux, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
      - name: Install operating system dependencies
        uses: ./.github/actions/install-dependencies
        with:
          fuseVersion: 2
      - name: Build Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: mountpoint-builder
          context: ./package
          # https://github.com/docker/buildx/issues/379
          ulimit: nofile=100000
      - name: Package an unofficial release
        run: docker run --mount type=bind,source=$(pwd),target=/mountpoint mountpoint-builder
      - name: Check release binary
        run: mkdir ./pkg-out && tar -xzf ./out/mount-s3*.tar.gz -C ./pkg-out && ./pkg-out/bin/mount-s3 --version
      - name: Upload unofficial packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages-${{ matrix.runner.name }}
          path:  ./out/*
          retention-days: 3
          if-no-files-found: error
